logging:
  level:
    com:
      _5icodes:
        starter:
          webmvc:
            log:
              LogFilter: trace
saturn:
  enabled: true
feign:
  client:
    config:
      baidu:
        localMapping: http://www.5icodes.com